# Generated by Django 3.0.5 on 2020-05-14 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(default='Football', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_short', models.CharField(default='', max_length=20)),
                ('comments', models.TextField(default='')),
                ('league', models.ManyToManyField(to='alp.League')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_team_goals', models.PositiveSmallIntegerField(default=0)),
                ('guest_team_goals', models.PositiveSmallIntegerField(default=0)),
                ('round_game', models.PositiveSmallIntegerField(default=0)),
                ('game_date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(default='')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='alp.Team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='alp.Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alp.League')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alp.Sport'),
        ),
    ]
