# Generated by Django 3.0.5 on 2020-04-14 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=100)),
                ('team_2', models.CharField(max_length=100)),
                ('team_1_goals', models.IntegerField(default=0)),
                ('team_2_goals', models.IntegerField(default=0)),
                ('round_game', models.IntegerField(default=0)),
                ('game_date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('team_short', models.CharField(max_length=10)),
            ],
        ),
    ]
