# Generated by Django 3.0.5 on 2020-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0002_auto_20200515_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
