# Generated by Django 3.0.5 on 2020-05-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0004_auto_20200516_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_game', 'game_date']},
        ),
    ]
