# Generated by Django 3.0.5 on 2020-05-19 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0005_auto_20200519_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
