# Generated by Django 3.0.5 on 2020-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0006_auto_20200519_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_date',
            field=models.DateTimeField(default=''),
        ),
    ]
