# Generated by Django 3.0.5 on 2020-05-19 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0007_auto_20200519_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 8, 59, 32, 610895, tzinfo=utc), null=True),
        ),
    ]
