# Generated by Django 3.0.5 on 2020-05-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0008_auto_20200519_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_game']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='game_date',
        ),
    ]
