# Generated by Django 3.0.5 on 2020-05-19 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0010_auto_20200519_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
