# Generated by Django 3.0.5 on 2020-05-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0014_match_game_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_game', 'game_date']},
        ),
    ]
