# Generated by Django 3.0.5 on 2020-05-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0016_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-publish_date']},
        ),
    ]
