# Generated by Django 3.0.5 on 2020-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0017_auto_20200519_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ManyToManyField(related_name='name', to='alp.League'),
        ),
    ]
