# Generated by Django 3.0.5 on 2020-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0020_auto_20200523_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_short',
            field=models.CharField(max_length=20),
        ),
    ]
