# Generated by Django 3.0.5 on 2020-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0021_auto_20200523_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_short',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
