# Generated by Django 3.0.5 on 2020-05-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0022_auto_20200523_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['sport_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name']},
        ),
    ]
