# Generated by Django 3.0.5 on 2020-05-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0023_auto_20200523_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(default='Football', on_delete=django.db.models.deletion.CASCADE, to='alp.Sport'),
        ),
    ]
